// Sample data for testing the dashboard without backend

export const sampleDrivers = [
  {
    id: 'd1',
    name: 'John Smith',
    email: 'john.smith@rapidaid.com',
    phone: '+1234567890',
    ambulanceNumber: 'A12',
    status: 'transporting',
    ambulanceStatus: 'transporting',
    currentLocation: {
      lat: 28.6139,
      lng: 77.2090,
    },
    license: 'DL-12345',
    type: 'ALS',
    routeHistory: '12.4 mi',
    lastUpdated: '1 min ago',
  },
  {
    id: 'd2',
    name: 'Sarah Johnson',
    email: 'sarah.j@rapidaid.com',
    phone: '+1234567891',
    ambulanceNumber: 'A09',
    status: 'available',
    ambulanceStatus: 'available',
    currentLocation: {
      lat: 28.6140,
      lng: 77.2091,
    },
    license: 'DL-12346',
    type: 'BLS',
    routeHistory: '0 mi',
    lastUpdated: '2 min ago',
  },
  {
    id: 'd3',
    name: 'Mike Davis',
    email: 'mike.d@rapidaid.com',
    phone: '+1234567892',
    ambulanceNumber: 'A15',
    status: 'en-route',
    ambulanceStatus: 'en-route',
    currentLocation: {
      lat: 28.6145,
      lng: 77.2095,
    },
    license: 'DL-12347',
    type: 'ALS',
    routeHistory: '8.2 mi',
    lastUpdated: '30 sec ago',
  },
  {
    id: 'd4',
    name: 'Emily Chen',
    email: 'emily.c@rapidaid.com',
    phone: '+1234567893',
    ambulanceNumber: 'A21',
    status: 'en-route',
    ambulanceStatus: 'en-route',
    currentLocation: {
      lat: 28.6150,
      lng: 77.2100,
    },
    license: 'DL-12348',
    type: 'BLS',
    routeHistory: '6.7 mi',
    lastUpdated: '45 sec ago',
  },
  {
    id: 'd5',
    name: 'Robert Wilson',
    email: 'robert.w@rapidaid.com',
    phone: '+1234567894',
    ambulanceNumber: 'A08',
    status: 'offline',
    ambulanceStatus: 'offline',
    currentLocation: null,
    license: 'DL-12349',
    type: 'ALS',
    routeHistory: '0 mi',
    lastUpdated: '5 min ago',
  },
];

export const samplePatients = [
  {
    id: 'p1',
    patientId: 'P56',
    name: 'Robert Martinez',
    age: 67,
    email: 'robert.m@email.com',
    phone: '+1987654321',
    emergencyType: 'Cardiac Arrest',
    location: { lat: 40.7580, lng: -73.9855 },
    assignedAmbulance: 'A12',
    pickupStatus: 'en-route',
    priority: 'HIGH',
    callTime: '14:23',
    createdAt: {
      seconds: Math.floor(Date.now() / 1000) - 3600,
    },
  },
  {
    id: 'p2',
    patientId: 'P72',
    name: 'Lisa Anderson',
    age: 34,
    email: 'lisa.a@email.com',
    phone: '+1987654322',
    emergencyType: 'Severe Trauma',
    location: { lat: 40.7570, lng: -73.9000 },
    assignedAmbulance: 'A15',
    pickupStatus: 'picked-up',
    priority: 'HIGH',
    callTime: '14:18',
    createdAt: {
      seconds: Math.floor(Date.now() / 1000) - 1800,
    },
  },
  {
    id: 'p3',
    patientId: 'P45',
    name: 'David Lee',
    age: 45,
    email: 'david.lee@email.com',
    phone: '+1987654323',
    emergencyType: 'Respiratory Distress',
    location: { lat: 40.7550, lng: -73.9800 },
    assignedAmbulance: 'A21',
    pickupStatus: 'en-route',
    priority: 'MEDIUM',
    callTime: '14:15',
    createdAt: {
      seconds: Math.floor(Date.now() / 1000) - 2700,
    },
  },
  {
    id: 'p4',
    patientId: 'P38',
    name: 'Maria Garcia',
    age: 52,
    email: 'maria.g@email.com',
    phone: '+1987654324',
    emergencyType: 'Stroke',
    location: { lat: 40.7500, lng: -73.9700 },
    assignedAmbulance: 'A09',
    pickupStatus: 'awaiting-pickup',
    priority: 'CRITICAL',
    callTime: '14:10',
    createdAt: {
      seconds: Math.floor(Date.now() / 1000) - 3600,
    },
  },
  {
    id: 'p5',
    patientId: 'P61',
    name: 'James Wilson',
    age: 29,
    email: 'james.w@email.com',
    phone: '+1987654325',
    emergencyType: 'Fracture',
    location: { lat: 40.7600, lng: -73.9900 },
    assignedAmbulance: 'A12',
    pickupStatus: 'arrived',
    priority: 'LOW',
    callTime: '13:45',
    createdAt: {
      seconds: Math.floor(Date.now() / 1000) - 7200,
    },
  },
  {
    id: 'p6',
    patientId: 'P49',
    name: 'Sarah Thompson',
    age: 41,
    email: 'sarah.t@email.com',
    phone: '+1987654326',
    emergencyType: 'Chest Pain',
    location: { lat: 40.7520, lng: -73.9750 },
    assignedAmbulance: 'A21',
    pickupStatus: 'en-route',
    priority: 'HIGH',
    callTime: '14:20',
    createdAt: {
      seconds: Math.floor(Date.now() / 1000) - 1200,
    },
  },
  {
    id: 'p7',
    patientId: 'P77',
    name: 'Ananya Verma',
    age: 31,
    email: 'ananya.v@email.com',
    phone: '+1987000001',
    emergencyType: 'Road Accident',
    location: { lat: 28.6328, lng: 77.2197 },
    assignedAmbulance: 'A21',
    pickupStatus: 'en-route',
    priority: 'HIGH',
    callTime: '14:28',
    createdAt: { seconds: Math.floor(Date.now() / 1000) - 900 },
  },
  {
    id: 'p8',
    patientId: 'P88',
    name: 'Rohan Desai',
    age: 27,
    email: 'rohan.d@email.com',
    phone: '+1987000002',
    emergencyType: 'Trauma',
    location: { lat: 19.076, lng: 72.8777 },
    assignedAmbulance: 'B11',
    pickupStatus: 'awaiting-pickup',
    priority: 'HIGH',
    callTime: '14:22',
    createdAt: { seconds: Math.floor(Date.now() / 1000) - 1400 },
  },
  {
    id: 'p9',
    patientId: 'P99',
    name: 'Priya Nair',
    age: 36,
    email: 'priya.n@email.com',
    phone: '+1987000003',
    emergencyType: 'Respiratory Distress',
    location: { lat: 12.9735, lng: 77.6082 },
    assignedAmbulance: 'C07',
    pickupStatus: 'en-route',
    priority: 'MEDIUM',
    callTime: '14:05',
    createdAt: { seconds: Math.floor(Date.now() / 1000) - 2200 },
  },
  {
    id: 'p10',
    patientId: 'P10',
    name: 'Kabir Malhotra',
    age: 29,
    email: 'kabir.m@email.com',
    phone: '+1987000004',
    emergencyType: 'Severe Injury',
    location: { lat: 17.4474, lng: 78.3762 },
    assignedAmbulance: 'D14',
    pickupStatus: 'en-route',
    priority: 'HIGH',
    callTime: '14:10',
    createdAt: { seconds: Math.floor(Date.now() / 1000) - 1600 },
  },
  {
    id: 'p11',
    patientId: 'P11',
    name: 'Neha Joshi',
    age: 33,
    email: 'neha.j@email.com',
    phone: '+1987000005',
    emergencyType: 'Fracture',
    location: { lat: 18.5204, lng: 73.8567 },
    assignedAmbulance: 'E03',
    pickupStatus: 'awaiting-pickup',
    priority: 'MEDIUM',
    callTime: '14:12',
    createdAt: { seconds: Math.floor(Date.now() / 1000) - 1300 },
  },
  {
    id: 'p12',
    patientId: 'P12',
    name: 'Arjun Iyer',
    age: 41,
    email: 'arjun.i@email.com',
    phone: '+1987000006',
    emergencyType: 'Cardiac Arrest',
    location: { lat: 13.0418, lng: 80.2337 },
    assignedAmbulance: 'F19',
    pickupStatus: 'en-route',
    priority: 'HIGH',
    callTime: '14:01',
    createdAt: { seconds: Math.floor(Date.now() / 1000) - 2800 },
  },
  {
    id: 'p13',
    patientId: 'P13',
    name: 'Pooja Shah',
    age: 38,
    email: 'pooja.s@email.com',
    phone: '+1987000007',
    emergencyType: 'Stroke',
    location: { lat: 23.0225, lng: 72.5714 },
    assignedAmbulance: 'G05',
    pickupStatus: 'en-route',
    priority: 'LOW',
    callTime: '13:55',
    createdAt: { seconds: Math.floor(Date.now() / 1000) - 3600 },
  },
  {
    id: 'p14',
    patientId: 'P14',
    name: 'Ananya Mukherjee',
    age: 30,
    email: 'ananya.m@email.com',
    phone: '+1987000008',
    emergencyType: 'Trauma',
    location: { lat: 22.5535, lng: 88.3507 },
    assignedAmbulance: 'H12',
    pickupStatus: 'en-route',
    priority: 'MEDIUM',
    callTime: '14:07',
    createdAt: { seconds: Math.floor(Date.now() / 1000) - 2400 },
  },
];

export const sampleEmergencies = [
  {
    id: 'e1',
    patientName: 'Robert Brown',
    patientId: 'p1',
    severity: 'High',
    status: 'in_progress',
    driverId: 'd1',
    assignedDriver: {
      name: 'John Smith',
      ambulanceNumber: 'AMB-001',
    },
    location: {
      lat: 28.6135,
      lng: 77.2085,
    },
    createdAt: {
      seconds: Math.floor(Date.now() / 1000) - 3600, // 1 hour ago
    },
    description: 'Chest pain, difficulty breathing',
  },
  {
    id: 'e2',
    patientName: 'Lisa Anderson',
    patientId: 'p2',
    severity: 'Medium',
    status: 'accepted',
    driverId: 'd2',
    assignedDriver: {
      name: 'Sarah Johnson',
      ambulanceNumber: 'AMB-002',
    },
    location: {
      lat: 28.6145,
      lng: 77.2100,
    },
    createdAt: {
      seconds: Math.floor(Date.now() / 1000) - 1800, // 30 minutes ago
    },
    description: 'Accident on highway',
  },
  {
    id: 'e3',
    patientName: 'David Lee',
    patientId: 'p3',
    severity: 'Critical',
    status: 'pending',
    driverId: null,
    assignedDriver: null,
    location: {
      lat: 28.6150,
      lng: 77.2105,
    },
    createdAt: {
      seconds: Math.floor(Date.now() / 1000) - 600, // 10 minutes ago
    },
    description: 'Unconscious, needs immediate attention',
  },
  {
    id: 'e4',
    patientName: 'Maria Garcia',
    patientId: 'p4',
    severity: 'Low',
    status: 'completed',
    driverId: 'd4',
    assignedDriver: {
      name: 'Emily Davis',
      ambulanceNumber: 'AMB-004',
    },
    location: {
      lat: 28.6120,
      lng: 77.2075,
    },
    createdAt: {
      seconds: Math.floor(Date.now() / 1000) - 86400, // 1 day ago
    },
    description: 'Minor injury, treated and discharged',
  },
];

export const sampleHospitals = [
  {
    id: 'delhi_h1',
    name: 'City General Hospital',
    address: 'Connaught Place, New Delhi',
    totalBeds: 200,
    availableBeds: 45,
    occupiedBeds: 155,
    occupancyRate: 78,
    location: { lat: 28.6200, lng: 77.2150 },
    wards: { icu: { total: 30, occupied: 20, available: 10 }, trauma: { total: 40, occupied: 30, available: 10 } },
  },
  {
    id: 'delhi_h2',
    name: 'Regional Medical Center',
    address: 'Karol Bagh, New Delhi',
    totalBeds: 150,
    availableBeds: 12,
    occupiedBeds: 138,
    occupancyRate: 92,
    location: { lat: 28.6100, lng: 77.2050 },
    wards: { icu: { total: 25, occupied: 18, available: 7 }, trauma: { total: 25, occupied: 20, available: 5 } },
  },
  {
    id: 'delhi_h3',
    name: 'Emergency Care Hospital',
    address: 'Chanakyapuri, New Delhi',
    totalBeds: 100,
    availableBeds: 8,
    occupiedBeds: 92,
    occupancyRate: 92,
    location: { lat: 28.6050, lng: 77.2000 },
    wards: { icu: { total: 20, occupied: 15, available: 5 }, trauma: { total: 15, occupied: 12, available: 3 } },
  },
  {
    id: 'delhi_h4',
    name: 'Community Health Center',
    address: 'South Extension, New Delhi',
    totalBeds: 80,
    availableBeds: 25,
    occupiedBeds: 55,
    occupancyRate: 69,
    location: { lat: 28.6250, lng: 77.2200 },
    wards: { icu: { total: 15, occupied: 10, available: 5 }, trauma: { total: 10, occupied: 7, available: 3 } },
  },
  { id: 'mumbai_h1', name: 'Marine Drive Hospital', address: 'Marine Drive, Mumbai', totalBeds: 220, availableBeds: 30, occupiedBeds: 190, occupancyRate: 86, location: { lat: 18.943, lng: 72.823 }, wards: { trauma: { total: 50, occupied: 40, available: 10 } } },
  { id: 'mumbai_h2', name: 'Colaba Medical Center', address: 'Colaba, Mumbai', totalBeds: 180, availableBeds: 22, occupiedBeds: 158, occupancyRate: 88, location: { lat: 18.906, lng: 72.814 }, wards: { trauma: { total: 40, occupied: 32, available: 8 } } },
  { id: 'blr_h1', name: 'MG Road Hospital', address: 'MG Road, Bengaluru', totalBeds: 160, availableBeds: 20, occupiedBeds: 140, occupancyRate: 87, location: { lat: 12.9755, lng: 77.605 }, wards: { trauma: { total: 35, occupied: 28, available: 7 } } },
  { id: 'blr_h2', name: 'Indiranagar Care', address: 'Indiranagar, Bengaluru', totalBeds: 140, availableBeds: 18, occupiedBeds: 122, occupancyRate: 87, location: { lat: 12.972, lng: 77.640 }, wards: { trauma: { total: 30, occupied: 20, available: 10 } } },
  { id: 'hyd_h1', name: 'HITEC City Hospital', address: 'HITEC City, Hyderabad', totalBeds: 200, availableBeds: 40, occupiedBeds: 160, occupancyRate: 80, location: { lat: 17.450, lng: 78.380 }, wards: { trauma: { total: 45, occupied: 35, available: 10 } } },
  { id: 'hyd_h2', name: 'Jubilee Hills Medical', address: 'Jubilee Hills, Hyderabad', totalBeds: 180, availableBeds: 28, occupiedBeds: 152, occupancyRate: 84, location: { lat: 17.430, lng: 78.410 }, wards: { trauma: { total: 40, occupied: 30, available: 10 } } },
  { id: 'pune_h1', name: 'FC Road Hospital', address: 'FC Road, Pune', totalBeds: 150, availableBeds: 25, occupiedBeds: 125, occupancyRate: 83, location: { lat: 18.520, lng: 73.854 }, wards: { trauma: { total: 30, occupied: 20, available: 10 } } },
  { id: 'pune_h2', name: 'Shivaji Nagar Care', address: 'Shivaji Nagar, Pune', totalBeds: 130, availableBeds: 20, occupiedBeds: 110, occupancyRate: 85, location: { lat: 18.530, lng: 73.850 }, wards: { trauma: { total: 25, occupied: 18, available: 7 } } },
  { id: 'chn_h1', name: 'T. Nagar Hospital', address: 'T. Nagar, Chennai', totalBeds: 170, availableBeds: 26, occupiedBeds: 144, occupancyRate: 85, location: { lat: 13.038, lng: 80.235 }, wards: { trauma: { total: 35, occupied: 26, available: 9 } } },
  { id: 'chn_h2', name: 'Adyar Medical Center', address: 'Adyar, Chennai', totalBeds: 160, availableBeds: 24, occupiedBeds: 136, occupancyRate: 85, location: { lat: 13.004, lng: 80.255 }, wards: { trauma: { total: 30, occupied: 20, available: 10 } } },
  { id: 'amd_h1', name: 'CG Road Hospital', address: 'CG Road, Ahmedabad', totalBeds: 140, availableBeds: 20, occupiedBeds: 120, occupancyRate: 86, location: { lat: 23.025, lng: 72.566 }, wards: { trauma: { total: 28, occupied: 20, available: 8 } } },
  { id: 'amd_h2', name: 'Navrangpura Care', address: 'Navrangpura, Ahmedabad', totalBeds: 150, availableBeds: 18, occupiedBeds: 132, occupancyRate: 88, location: { lat: 23.031, lng: 72.560 }, wards: { trauma: { total: 30, occupied: 22, available: 8 } } },
  { id: 'kol_h1', name: 'Park Street Hospital', address: 'Park Street, Kolkata', totalBeds: 180, availableBeds: 30, occupiedBeds: 150, occupancyRate: 83, location: { lat: 22.553, lng: 88.352 }, wards: { trauma: { total: 40, occupied: 30, available: 10 } } },
  { id: 'kol_h2', name: 'Salt Lake Medical', address: 'Salt Lake, Kolkata', totalBeds: 160, availableBeds: 25, occupiedBeds: 135, occupancyRate: 84, location: { lat: 22.586, lng: 88.417 }, wards: { trauma: { total: 35, occupied: 26, available: 9 } } },
  { id: 'jpr_h1', name: 'MI Road Hospital', address: 'MI Road, Jaipur', totalBeds: 150, availableBeds: 24, occupiedBeds: 126, occupancyRate: 84, location: { lat: 26.915, lng: 75.788 }, wards: { trauma: { total: 32, occupied: 24, available: 8 } } },
  { id: 'jpr_h2', name: 'C-Scheme Care', address: 'C-Scheme, Jaipur', totalBeds: 140, availableBeds: 22, occupiedBeds: 118, occupancyRate: 84, location: { lat: 26.913, lng: 75.783 }, wards: { trauma: { total: 28, occupied: 20, available: 8 } } },
  { id: 'chd_h1', name: 'Sector 32 Hospital', address: 'Sector 32, Chandigarh', totalBeds: 160, availableBeds: 28, occupiedBeds: 132, occupancyRate: 83, location: { lat: 30.739, lng: 76.791 }, wards: { trauma: { total: 36, occupied: 28, available: 8 } } },
  { id: 'chd_h2', name: 'PGI Care', address: 'Sector 12, Chandigarh', totalBeds: 180, availableBeds: 30, occupiedBeds: 150, occupancyRate: 83, location: { lat: 30.764, lng: 76.773 }, wards: { trauma: { total: 40, occupied: 32, available: 8 } } },
];

// Aggregate hospital capacity data
export const sampleHospitalCapacity = {
  totalBeds: 530,
  availableBeds: 90,
  occupiedBeds: 440,
  occupancyRate: 83,
  incoming: 8,
  wards: {
    icu: { total: 90, occupied: 63, available: 27, occupancyRate: 70 },
    emergency: { total: 145, occupied: 108, available: 37, occupancyRate: 74 },
    general: { total: 205, occupied: 157, available: 48, occupancyRate: 77 },
    trauma: { total: 90, occupied: 69, available: 21, occupancyRate: 77 },
  },
};

export const sampleDashboardMetrics = {
  totalDrivers: 4,
  onDutyDrivers: 3,
  totalPatients: 5,
  totalEmergencies: 4,
  activeEmergencies: 3,
  completedEmergencies: 1,
  liveTracking: 3,
  totalHospitals: 4,
  availableBeds: 90,
};

// Helper function to simulate API delay
export const simulateDelay = (ms = 500) => {
  return new Promise((resolve) => setTimeout(resolve, ms));
};

